name: Build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pyinstaller
        run: pip install -r conans/requirements.txt -U

      - name: Build
        run: pyinstaller --onefile conans/conan.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Conan_${{ matrix.os }}
          path: dist/*
          if-no-files-found: error
